### ISSUE TITLE
Add Initial Setup

### ISSUE THREAD

**Issue by KozielGPC** [KozielGPC/championship-platform#1]
### Description

Add initial setup to start project using FastAPI on backend and ReactJS on frontend. Setup folders and dependencies

### Tasks

- [x] Start FastAPI Project
- [x] Start React Project
- [x] Configure React + FastAPI  environment
- [x] Update Changelog
